# Generated by Django 4.2 on 2023-05-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_id_alter_booking_no_of_guests_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='MenuItem',
        ),
    ]
